/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationsStationCodeRouteImport } from './routes/stations.$stationCode'
import { Route as ApiStationsStationCodeDayRouteImport } from './routes/api.stations.$stationCode.day'

const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationCodeRoute = StationsStationCodeRouteImport.update({
  id: '/stations/$stationCode',
  path: '/stations/$stationCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStationsStationCodeDayRoute =
  ApiStationsStationCodeDayRouteImport.update({
    id: '/api/stations/$stationCode/day',
    path: '/api/stations/$stationCode/day',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/stations/$stationCode': typeof StationsStationCodeRoute
  '/api/stations/$stationCode/day': typeof ApiStationsStationCodeDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/stations/$stationCode': typeof StationsStationCodeRoute
  '/api/stations/$stationCode/day': typeof ApiStationsStationCodeDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/stations/$stationCode': typeof StationsStationCodeRoute
  '/api/stations/$stationCode/day': typeof ApiStationsStationCodeDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/stations/$stationCode'
    | '/api/stations/$stationCode/day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faq' | '/stations/$stationCode' | '/api/stations/$stationCode/day'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/stations/$stationCode'
    | '/api/stations/$stationCode/day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  StationsStationCodeRoute: typeof StationsStationCodeRoute
  ApiStationsStationCodeDayRoute: typeof ApiStationsStationCodeDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationCode': {
      id: '/stations/$stationCode'
      path: '/stations/$stationCode'
      fullPath: '/stations/$stationCode'
      preLoaderRoute: typeof StationsStationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stations/$stationCode/day': {
      id: '/api/stations/$stationCode/day'
      path: '/api/stations/$stationCode/day'
      fullPath: '/api/stations/$stationCode/day'
      preLoaderRoute: typeof ApiStationsStationCodeDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  StationsStationCodeRoute: StationsStationCodeRoute,
  ApiStationsStationCodeDayRoute: ApiStationsStationCodeDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
